"""Translation provenance: keep machine and human rows apart

Revision ID: 063c0fb1d082
Revises: d4a91c73e502
Create Date: 2026-08-23 13:25:09.271343+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '063c0fb1d082'
down_revision: str | None = 'd4a91c73e502'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Everything already in the table was written by a person, so that is the
    # backfill. The default is dropped straight after: provenance is a fact the
    # writer states, not something the schema should quietly supply.
    op.add_column(
        'content_translations',
        sa.Column('provenance', sa.String(length=16), nullable=False, server_default='human'),
    )
    op.alter_column('content_translations', 'provenance', server_default=None)
    op.drop_constraint(op.f('uq_content_translations_target'), 'content_translations', type_='unique')
    op.create_unique_constraint('uq_content_translations_target', 'content_translations', ['locale', 'target_type', 'target_key', 'field', 'provenance'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_content_translations_target', 'content_translations', type_='unique')
    op.create_unique_constraint(op.f('uq_content_translations_target'), 'content_translations', ['locale', 'target_type', 'target_key', 'field'], postgresql_nulls_not_distinct=False)
    op.drop_column('content_translations', 'provenance')
    # ### end Alembic commands ###
