"""courses, areas of study and their curriculum structure

Revision ID: 94dbbe2277d9
Revises: e7c3f1a8b2d5
Create Date: 2026-08-28 11:51:28.815094+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94dbbe2277d9'
down_revision: str | None = 'e7c3f1a8b2d5'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_of_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aos_code', sa.String(length=24), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('aos_type', sa.String(length=64), nullable=True),
    sa.Column('study_level', sa.String(length=64), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.String(length=200), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('handbook_version', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aos_code', 'academic_year', name='uq_aos_code_year')
    )
    op.create_index(op.f('ix_areas_of_study_academic_year'), 'areas_of_study', ['academic_year'], unique=False)
    op.create_index(op.f('ix_areas_of_study_aos_code'), 'areas_of_study', ['aos_code'], unique=False)
    op.create_index(op.f('ix_areas_of_study_aos_type'), 'areas_of_study', ['aos_type'], unique=False)
    op.create_index(op.f('ix_areas_of_study_content_hash'), 'areas_of_study', ['content_hash'], unique=False)
    op.create_index(op.f('ix_areas_of_study_faculty'), 'areas_of_study', ['faculty'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('abbreviated_name', sa.String(length=64), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.Column('cricos_code', sa.String(length=32), nullable=True),
    sa.Column('aqf_level', sa.String(length=64), nullable=True),
    sa.Column('course_type', sa.String(length=64), nullable=True),
    sa.Column('faculty', sa.String(length=200), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('campuses', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('structure_text', sa.Text(), nullable=True),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('handbook_version', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code', 'academic_year', name='uq_courses_code_year')
    )
    op.create_index(op.f('ix_courses_academic_year'), 'courses', ['academic_year'], unique=False)
    op.create_index('ix_courses_campuses', 'courses', ['campuses'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_courses_content_hash'), 'courses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.create_index(op.f('ix_courses_course_type'), 'courses', ['course_type'], unique=False)
    op.create_index(op.f('ix_courses_faculty'), 'courses', ['faculty'], unique=False)
    op.create_table('curriculum_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('area_of_study_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('footnote', sa.Text(), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.Column('credit_points_max', sa.Integer(), nullable=True),
    sa.Column('connector', sa.String(length=8), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('(course_id IS NULL) <> (area_of_study_id IS NULL)', name='ck_curriculum_containers_one_parent'),
    sa.ForeignKeyConstraint(['area_of_study_id'], ['areas_of_study.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_containers_area_of_study_id'), 'curriculum_containers', ['area_of_study_id'], unique=False)
    op.create_index(op.f('ix_curriculum_containers_course_id'), 'curriculum_containers', ['course_id'], unique=False)
    op.create_index('ix_curriculum_containers_parent', 'curriculum_containers', ['parent_id'], unique=False)
    op.create_table('curriculum_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=24), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=True),
    sa.Column('item_url', sa.String(length=500), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.Column('connector', sa.String(length=8), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['curriculum_containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_items_container_id'), 'curriculum_items', ['container_id'], unique=False)
    op.create_index(op.f('ix_curriculum_items_item_code'), 'curriculum_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_curriculum_items_item_type'), 'curriculum_items', ['item_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_items_item_type'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_item_code'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_container_id'), table_name='curriculum_items')
    op.drop_table('curriculum_items')
    op.drop_index('ix_curriculum_containers_parent', table_name='curriculum_containers')
    op.drop_index(op.f('ix_curriculum_containers_course_id'), table_name='curriculum_containers')
    op.drop_index(op.f('ix_curriculum_containers_area_of_study_id'), table_name='curriculum_containers')
    op.drop_table('curriculum_containers')
    op.drop_index(op.f('ix_courses_faculty'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_type'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_content_hash'), table_name='courses')
    op.drop_index('ix_courses_campuses', table_name='courses', postgresql_using='gin')
    op.drop_index(op.f('ix_courses_academic_year'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_areas_of_study_faculty'), table_name='areas_of_study')
    op.drop_index(op.f('ix_areas_of_study_content_hash'), table_name='areas_of_study')
    op.drop_index(op.f('ix_areas_of_study_aos_type'), table_name='areas_of_study')
    op.drop_index(op.f('ix_areas_of_study_aos_code'), table_name='areas_of_study')
    op.drop_index(op.f('ix_areas_of_study_academic_year'), table_name='areas_of_study')
    op.drop_table('areas_of_study')
    # ### end Alembic commands ###
