"""Initial schema: handbook, official knowledge, community and crawl bookkeeping.

Revision ID: 9ae3b5e8984d
Revises: 
Create Date: 2026-08-22 21:25:13.976630+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9ae3b5e8984d'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Trigram indexes on unit and page titles need this, and it has to exist
    # before the CREATE INDEX statements further down.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crawl_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_key', sa.String(length=600), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('transport', sa.String(length=24), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_history_job_id'), 'crawl_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawl_history_outcome'), 'crawl_history', ['outcome'], unique=False)
    op.create_index(op.f('ix_crawl_history_target_key'), 'crawl_history', ['target_key'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('targets', sa.Integer(), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('changed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=24), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_job_type'), 'crawl_jobs', ['job_type'], unique=False)
    op.create_table('official_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('source_change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_key', sa.String(length=600), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=False),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_change_events_target_key'), 'source_change_events', ['target_key'], unique=False)
    op.create_index(op.f('ix_source_change_events_target_type'), 'source_change_events', ['target_type'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=16), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('credit_points', sa.String(length=16), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('faculty', sa.String(length=200), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('subject_prefix', sa.String(length=8), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('areas_of_study', sa.Text(), nullable=True),
    sa.Column('teaching_approach', sa.Text(), nullable=True),
    sa.Column('workload_requirements', sa.Text(), nullable=True),
    sa.Column('assessment_summary', sa.Text(), nullable=True),
    sa.Column('assessment_static_text', sa.Text(), nullable=True),
    sa.Column('has_exam', sa.Boolean(), nullable=True),
    sa.Column('handbook_version', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(unit_code, '') || ' ' || coalesce(title, '') || ' ' || coalesce(overview, '') || ' ' || coalesce(areas_of_study, ''))", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_code', 'academic_year', name='uq_units_code_year')
    )
    op.create_index(op.f('ix_units_academic_year'), 'units', ['academic_year'], unique=False)
    op.create_index(op.f('ix_units_content_hash'), 'units', ['content_hash'], unique=False)
    op.create_index(op.f('ix_units_faculty'), 'units', ['faculty'], unique=False)
    op.create_index(op.f('ix_units_has_exam'), 'units', ['has_exam'], unique=False)
    op.create_index('ix_units_search_vector', 'units', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_units_subject_prefix'), 'units', ['subject_prefix'], unique=False)
    op.create_index('ix_units_title_trgm', 'units', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nickname', sa.String(length=48), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('unit_code', sa.String(length=16), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, '') || ' ' || coalesce(unit_code, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_category'), 'community_posts', ['category'], unique=False)
    op.create_index('ix_community_posts_search_vector', 'community_posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_community_posts_unit_code'), 'community_posts', ['unit_code'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_vote_once')
    )
    op.create_index(op.f('ix_community_votes_user_id'), 'community_votes', ['user_id'], unique=False)
    op.create_table('official_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=600), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refresh_tier', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(category, '') || ' ' || coalesce(clean_text, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['official_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_official_pages_category'), 'official_pages', ['category'], unique=False)
    op.create_index(op.f('ix_official_pages_content_hash'), 'official_pages', ['content_hash'], unique=False)
    op.create_index('ix_official_pages_search_vector', 'official_pages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_official_pages_source_id'), 'official_pages', ['source_id'], unique=False)
    op.create_index('ix_official_pages_title_trgm', 'official_pages', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('unit_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_activities_unit_id'), 'unit_activities', ['unit_id'], unique=False)
    op.create_table('unit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('assessment_type', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('hurdle', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_outcomes', sa.String(length=120), nullable=True),
    sa.Column('offering_scope', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_assessments_assessment_type'), 'unit_assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_unit_assessments_unit_id'), 'unit_assessments', ['unit_id'], unique=False)
    op.create_table('unit_learning_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_learning_outcomes_unit_id'), 'unit_learning_outcomes', ['unit_id'], unique=False)
    op.create_table('unit_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('offering_code', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('campus', sa.String(length=120), nullable=True),
    sa.Column('teaching_period', sa.String(length=120), nullable=True),
    sa.Column('attendance_mode', sa.String(length=120), nullable=True),
    sa.Column('study_level', sa.String(length=120), nullable=True),
    sa.Column('offered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_offerings_campus'), 'unit_offerings', ['campus'], unique=False)
    op.create_index(op.f('ix_unit_offerings_teaching_period'), 'unit_offerings', ['teaching_period'], unique=False)
    op.create_index(op.f('ix_unit_offerings_unit_id'), 'unit_offerings', ['unit_id'], unique=False)
    op.create_table('unit_requisite_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('requisite_type', sa.String(length=40), nullable=False),
    sa.Column('connector', sa.String(length=8), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_requisite_groups_requisite_type'), 'unit_requisite_groups', ['requisite_type'], unique=False)
    op.create_index(op.f('ix_unit_requisite_groups_unit_id'), 'unit_requisite_groups', ['unit_id'], unique=False)
    op.create_table('unit_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'content_hash', name='uq_unit_versions_unit_hash')
    )
    op.create_index(op.f('ix_unit_versions_unit_id'), 'unit_versions', ['unit_id'], unique=False)
    op.create_table('community_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_answers_author_id'), 'community_answers', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_answers_post_id'), 'community_answers', ['post_id'], unique=False)
    op.create_table('community_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_bookmark_once')
    )
    op.create_index(op.f('ix_community_bookmarks_post_id'), 'community_bookmarks', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_bookmarks_user_id'), 'community_bookmarks', ['user_id'], unique=False)
    op.create_table('community_post_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['community_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag')
    )
    op.create_index(op.f('ix_community_post_tags_post_id'), 'community_post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_post_tags_tag_id'), 'community_post_tags', ['tag_id'], unique=False)
    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('question', sa.String(length=400), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('official_page_id', sa.Integer(), nullable=True),
    sa.Column('official_url', sa.String(length=600), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(question, '') || ' ' || coalesce(answer, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['official_page_id'], ['official_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_faq_entries_category'), 'faq_entries', ['category'], unique=False)
    op.create_index('ix_faq_entries_search_vector', 'faq_entries', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('official_page_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['official_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_page_versions_page_id'), 'official_page_versions', ['page_id'], unique=False)
    op.create_table('unit_requisite_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=32), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('item_type', sa.String(length=40), nullable=True),
    sa.Column('item_url', sa.String(length=500), nullable=True),
    sa.Column('credit_points', sa.String(length=16), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['unit_requisite_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_requisite_items_group_id'), 'unit_requisite_items', ['group_id'], unique=False)
    op.create_index(op.f('ix_unit_requisite_items_item_code'), 'unit_requisite_items', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # pg_trgm is left installed on purpose: another database on the same server
    # may be using it, and dropping a shared extension on a rollback is rude.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_requisite_items_item_code'), table_name='unit_requisite_items')
    op.drop_index(op.f('ix_unit_requisite_items_group_id'), table_name='unit_requisite_items')
    op.drop_table('unit_requisite_items')
    op.drop_index(op.f('ix_official_page_versions_page_id'), table_name='official_page_versions')
    op.drop_table('official_page_versions')
    op.drop_index('ix_faq_entries_search_vector', table_name='faq_entries', postgresql_using='gin')
    op.drop_index(op.f('ix_faq_entries_category'), table_name='faq_entries')
    op.drop_table('faq_entries')
    op.drop_index(op.f('ix_community_post_tags_tag_id'), table_name='community_post_tags')
    op.drop_index(op.f('ix_community_post_tags_post_id'), table_name='community_post_tags')
    op.drop_table('community_post_tags')
    op.drop_index(op.f('ix_community_bookmarks_user_id'), table_name='community_bookmarks')
    op.drop_index(op.f('ix_community_bookmarks_post_id'), table_name='community_bookmarks')
    op.drop_table('community_bookmarks')
    op.drop_index(op.f('ix_community_answers_post_id'), table_name='community_answers')
    op.drop_index(op.f('ix_community_answers_author_id'), table_name='community_answers')
    op.drop_table('community_answers')
    op.drop_index(op.f('ix_unit_versions_unit_id'), table_name='unit_versions')
    op.drop_table('unit_versions')
    op.drop_index(op.f('ix_unit_requisite_groups_unit_id'), table_name='unit_requisite_groups')
    op.drop_index(op.f('ix_unit_requisite_groups_requisite_type'), table_name='unit_requisite_groups')
    op.drop_table('unit_requisite_groups')
    op.drop_index(op.f('ix_unit_offerings_unit_id'), table_name='unit_offerings')
    op.drop_index(op.f('ix_unit_offerings_teaching_period'), table_name='unit_offerings')
    op.drop_index(op.f('ix_unit_offerings_campus'), table_name='unit_offerings')
    op.drop_table('unit_offerings')
    op.drop_index(op.f('ix_unit_learning_outcomes_unit_id'), table_name='unit_learning_outcomes')
    op.drop_table('unit_learning_outcomes')
    op.drop_index(op.f('ix_unit_assessments_unit_id'), table_name='unit_assessments')
    op.drop_index(op.f('ix_unit_assessments_assessment_type'), table_name='unit_assessments')
    op.drop_table('unit_assessments')
    op.drop_index(op.f('ix_unit_activities_unit_id'), table_name='unit_activities')
    op.drop_table('unit_activities')
    op.drop_index('ix_official_pages_title_trgm', table_name='official_pages', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_official_pages_source_id'), table_name='official_pages')
    op.drop_index('ix_official_pages_search_vector', table_name='official_pages', postgresql_using='gin')
    op.drop_index(op.f('ix_official_pages_content_hash'), table_name='official_pages')
    op.drop_index(op.f('ix_official_pages_category'), table_name='official_pages')
    op.drop_table('official_pages')
    op.drop_index(op.f('ix_community_votes_user_id'), table_name='community_votes')
    op.drop_table('community_votes')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_community_posts_unit_code'), table_name='community_posts')
    op.drop_index('ix_community_posts_search_vector', table_name='community_posts', postgresql_using='gin')
    op.drop_index(op.f('ix_community_posts_category'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.drop_index('ix_units_title_trgm', table_name='units', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_units_subject_prefix'), table_name='units')
    op.drop_index('ix_units_search_vector', table_name='units', postgresql_using='gin')
    op.drop_index(op.f('ix_units_has_exam'), table_name='units')
    op.drop_index(op.f('ix_units_faculty'), table_name='units')
    op.drop_index(op.f('ix_units_content_hash'), table_name='units')
    op.drop_index(op.f('ix_units_academic_year'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_source_change_events_target_type'), table_name='source_change_events')
    op.drop_index(op.f('ix_source_change_events_target_key'), table_name='source_change_events')
    op.drop_table('source_change_events')
    op.drop_table('official_sources')
    op.drop_index(op.f('ix_crawl_jobs_job_type'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_crawl_history_target_key'), table_name='crawl_history')
    op.drop_index(op.f('ix_crawl_history_outcome'), table_name='crawl_history')
    op.drop_index(op.f('ix_crawl_history_job_id'), table_name='crawl_history')
    op.drop_table('crawl_history')
    op.drop_table('community_tags')
    # ### end Alembic commands ###
