"""Chinese search text

Revision ID: a7f3c19b2e04
Revises: 12fcfb2805dd
Create Date: 2026-08-29 00:16:57.902465+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a7f3c19b2e04'
down_revision: str | None = '12fcfb2805dd'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_pages', sa.Column('search_zh', sa.Text(), nullable=True))
    op.create_index('ix_official_pages_search_zh_trgm', 'official_pages', ['search_zh'], unique=False, postgresql_using='gin', postgresql_ops={'search_zh': 'gin_trgm_ops'})
    op.add_column('units', sa.Column('search_zh', sa.Text(), nullable=True))
    op.create_index('ix_units_search_zh_trgm', 'units', ['search_zh'], unique=False, postgresql_using='gin', postgresql_ops={'search_zh': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_units_search_zh_trgm', table_name='units', postgresql_using='gin', postgresql_ops={'search_zh': 'gin_trgm_ops'})
    op.drop_column('units', 'search_zh')
    op.drop_index('ix_official_pages_search_zh_trgm', table_name='official_pages', postgresql_using='gin', postgresql_ops={'search_zh': 'gin_trgm_ops'})
    op.drop_column('official_pages', 'search_zh')
    # ### end Alembic commands ###
