"""Profile avatar and bio

Revision ID: b5e21d9c4f08
Revises: a7f3c19b2e04
Create Date: 2026-08-29 01:06:30.237409+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5e21d9c4f08'
down_revision: str | None = 'a7f3c19b2e04'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_file', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_file')
    # ### end Alembic commands ###
