"""Accounts, email verification codes and notifications

Revision ID: be5d8c40c314
Revises: 9ae3b5e8984d
Create Date: 2026-08-23 04:17:31.115165+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be5d8c40c314'
down_revision: str | None = '9ae3b5e8984d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_email'), 'email_verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_purpose'), 'email_verification_codes', ['purpose'], unique=False)
    op.create_index('ix_evc_created_at', 'email_verification_codes', ['created_at'], unique=False)
    op.create_index('ix_evc_lookup', 'email_verification_codes', ['email', 'purpose', 'consumed_at', 'expires_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('actor_nickname', sa.String(length=48), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('post_title', sa.String(length=300), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('excerpt', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_post_id'), 'notifications', ['post_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_community_posts_category_feed', 'community_posts', ['category', 'is_hidden', 'updated_at'], unique=False)
    op.create_index('ix_community_posts_feed', 'community_posts', ['is_hidden', 'is_pinned', 'updated_at'], unique=False)
    op.create_index('ix_community_posts_unit_feed', 'community_posts', ['unit_code', 'is_hidden', 'updated_at'], unique=False)
    # server_default so the column can be added to a table that already has
    # rows; it is dropped straight after, because the value belongs to the
    # application, not to the schema.
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('users', 'token_version', server_default=None)
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'token_version')
    op.drop_index('ix_community_posts_unit_feed', table_name='community_posts')
    op.drop_index('ix_community_posts_feed', table_name='community_posts')
    op.drop_index('ix_community_posts_category_feed', table_name='community_posts')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_post_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_evc_lookup', table_name='email_verification_codes')
    op.drop_index('ix_evc_created_at', table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_purpose'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_email'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
