"""Human-written translations of source content

Revision ID: d4a91c73e502
Revises: c1f7a20b9d34
Create Date: 2026-08-23 06:09:56.292291+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd4a91c73e502'
down_revision: str | None = 'c1f7a20b9d34'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_key', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('translator', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locale', 'target_type', 'target_key', 'field', name='uq_content_translations_target')
    )
    op.create_index('ix_content_translations_lookup', 'content_translations', ['target_type', 'target_key', 'locale', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_translations_lookup', table_name='content_translations')
    op.drop_table('content_translations')
    # ### end Alembic commands ###
